name: CD

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            
            cd /home/ilya/catty-reminders-app
            
            REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
            IMAGE_FULL="ghcr.io/${REPO_OWNER}/catty-reminders-app:${{ github.sha }}"
            
            export IMAGE="${IMAGE_FULL}"
            export APP_CONTAINER_NAME=catty-app
            export MARIADB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}
            export MARIADB_USER=${{ secrets.DB_USER }}
            export MARIADB_PASSWORD=${{ secrets.DB_PASSWORD }}
            export MARIADB_DATABASE=catty_reminders
            export HOST_DB_PORT=3306
            export CONTEINER_DB_PORT=3306
            export HOST_APP_PORT=8181
            export CONTEINER_APP_PORT=8181
            
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            docker compose pull
            docker compose up -d --force-recreate --remove-orphans
            
            docker system prune -f
